const mockEvents = {
  city: {
    id: 1007700,
    city: "München",
    lat: 48.14,
    lon: 11.58,
    state: "",
    country: "de",
    zip: "meetup3",
    member_count: 1257,
  },
  events: [
    {
      created: 1579163951000,
      duration: 10800000,
      id: "ddhzmrybcgbtb",
      name: "Drupal User Group Munich @EineWeltHaus",
      rsvp_limit: 15,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1586970000000,
      local_date: "2020-04-15",
      local_time: "19:00",
      updated: 1583154863000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 3,
      venue: {
        id: 26078691,
        name: "EineWeltHaus",
        lat: 48.137691497802734,
        lon: 11.55286979675293,
        repinned: true,
        address_1: "Schwanthalerstraße 80",
        city: "München",
        country: "de",
        localized_country_name: "Germany",
      },
      group: {
        created: 1410086988000,
        name: "München Drupal User Group Meetup",
        id: 16845232,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Munchen-Drupal-User-Group-Meetup",
        who: "Drupalistas",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link:
        "https://www.meetup.com/Munchen-Drupal-User-Group-Meetup/events/ddhzmrybcgbtb/",
      description:
        "<p>Das Meetup ist sowohl für Drupal-AnwenderInnen, -EntwicklerInnnen, -EinsteigerInnen als auch Professionals geeignet. Wir reden nicht nur über Drupal, sondern auch über Community, React, Vue.js, Docker, Symfony, PHP, UX und viele andere Dinge. Andere Communities sind bei uns herzlich Willkommen!</p> <p>The meetup is for any level of Drupal user. We are not talking Drupal only but also about community, React, Vue.js, Docker Symfony, PHP, UX and much more stuff. Other communities are very welcome.</p> <p>---<br/>Vortrag 1 / Talk 1 -<br/>---<br/>Vortrag 2 /Talk 2 - tbd<br/>---</p> <p>Wir suchen immer nach interessanten Themen! Wenn du interessiert daran bist, einen Vortrag oder ein interessantes Projekt vorzustellen (deutsch oder englisch entscheidest du!), melde dich bei uns.</p> <p>Im Anschluss der Talks gibt es genügend Zeit für Diskussion und Networking. Wir sehen uns dort!</p> <p>---</p> <p>If you are interested in giving a talk or to speak about a interesting project, drop us a line. We are always looking for talks.</p> <p>Followed by discussion and networking.<br/>See you there!</p> ",
      how_to_find_us:
        "Raum 109. Bitte den Raumbelegungsplan am Eingang beachten.",
      visibility: "public",
      member_pay_fee: false,
    },
    {
      created: 1564222784000,
      duration: 10800000,
      id: "sqlrfrybchbfb",
      name: "Repair Café Schwabing",
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1588507200000,
      local_date: "2020-05-03",
      local_time: "14:00",
      updated: 1564222784000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      venue: {
        id: 26538112,
        name: "Seidlvilla",
        lat: 48.15855026245117,
        lon: 11.587692260742188,
        repinned: false,
        address_1: "Nikolaiplatz 1b",
        city: "München ",
        country: "DE",
        localized_country_name: "Germany",
      },
      group: {
        created: 1490371801000,
        name: "Repair Café Meetup",
        id: 22994509,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Repair-Cafe-Meetup",
        who: "Mitglieder",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link: "https://www.meetup.com/Repair-Cafe-Meetup/events/sqlrfrybchbfb/",
      description:
        "<p>Jeden ersten Sonntag ab 14 Uhr bis 17 Uhr finde in der Seidlvilla in Schwabing unser Repair Café statt. Bringt Eure kaputten Uhren, Elektro Kleinteile, Haushaltsgeräte, Kleidungsstücke, Taschen, Textilien sowie Laptops oder Handys die repariert werden müssen. Wenn ihr selbst wisst, wie es geht, und mitmachen wollt, freuen wir uns auf deine Mithilfe bei reparieren hierzu bitte vorab melden unter [masked]. </p> <p>Every first Sunday from 2pm to 5pm the Repair Café Schwabing takes place in the Seidlvilla in Schwabing (U3 and 6 Münchner Freiheit). Bring your broken watches, electronic items, household items, clothes, bags and other textiles as well as laptops and phones. If you know how to repair and want to join in, we are looking forward to your contribution. Please let us know in advance, if you will be part of the repair team: [masked] and we will give you further information.</p> ",
      how_to_find_us: "zwischen Münchner Freiheit und Giselastraße",
      visibility: "public",
      member_pay_fee: false,
    },
    {
      created: 1564222784000,
      duration: 10800000,
      id: "sqlrfrybcjbkb",
      name: "Repair Café Schwabing",
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1591531200000,
      local_date: "2020-06-07",
      local_time: "14:00",
      updated: 1564222784000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      venue: {
        id: 26538112,
        name: "Seidlvilla",
        lat: 48.15855026245117,
        lon: 11.587692260742188,
        repinned: false,
        address_1: "Nikolaiplatz 1b",
        city: "München ",
        country: "DE",
        localized_country_name: "Germany",
      },
      group: {
        created: 1490371801000,
        name: "Repair Café Meetup",
        id: 22994509,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Repair-Cafe-Meetup",
        who: "Mitglieder",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link: "https://www.meetup.com/Repair-Cafe-Meetup/events/sqlrfrybcjbkb/",
      description:
        "<p>Jeden ersten Sonntag ab 14 Uhr bis 17 Uhr finde in der Seidlvilla in Schwabing unser Repair Café statt. Bringt Eure kaputten Uhren, Elektro Kleinteile, Haushaltsgeräte, Kleidungsstücke, Taschen, Textilien sowie Laptops oder Handys die repariert werden müssen. Wenn ihr selbst wisst, wie es geht, und mitmachen wollt, freuen wir uns auf deine Mithilfe bei reparieren hierzu bitte vorab melden unter [masked]. </p> <p>Every first Sunday from 2pm to 5pm the Repair Café Schwabing takes place in the Seidlvilla in Schwabing (U3 and 6 Münchner Freiheit). Bring your broken watches, electronic items, household items, clothes, bags and other textiles as well as laptops and phones. If you know how to repair and want to join in, we are looking forward to your contribution. Please let us know in advance, if you will be part of the repair team: [masked] and we will give you further information.</p> ",
      how_to_find_us: "zwischen Münchner Freiheit und Giselastraße",
      visibility: "public",
      member_pay_fee: false,
    },
    {
      created: 1579163951000,
      duration: 10800000,
      id: "ddhzmrybchbbc",
      name: "Drupal User Group Munich @Acquia & The Digitale",
      rsvp_limit: 20,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1589994000000,
      local_date: "2020-05-20",
      local_time: "19:00",
      updated: 1583154607000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 3,
      venue: {
        id: 26867219,
        name: "Acquia GmbH",
        lat: 48.143211364746094,
        lon: 11.538675308227539,
        repinned: true,
        address_1: "Erika-Mann-Straße 53",
        city: "München",
        country: "de",
        localized_country_name: "Germany",
      },
      group: {
        created: 1410086988000,
        name: "München Drupal User Group Meetup",
        id: 16845232,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Munchen-Drupal-User-Group-Meetup",
        who: "Drupalistas",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link:
        "https://www.meetup.com/Munchen-Drupal-User-Group-Meetup/events/ddhzmrybchbbc/",
      description:
        "<p>Das Meetup ist sowohl für Drupal-AnwenderInnen, -EntwicklerInnnen, -EinsteigerInnen als auch Professionals geeignet. Wir reden nicht nur über Drupal, sondern auch über Community, React, Vue.js, Docker, Symfony, PHP, UX und viele andere Dinge. Andere Communities sind bei uns herzlich Willkommen!</p> <p>The meetup is for any level of Drupal user. We are not talking Drupal only but also about community, React, Vue.js, Docker Symfony, PHP, UX and much more stuff. Other communities are very welcome.</p> <p>---<br/>Vorstellung von Acquia Team Central Europe und The Digitale<br/>---<br/>Vortrag 1 / Talk 1 - Ein neuer Ansatz fürs Site Building mit Acquia Cohesion",
      visibility: "public",
      member_pay_fee: false,
    },
    {
      created: 1580849312000,
      duration: 10800000,
      fee: {
        accepts: "cash",
        amount: 20,
        currency: "EUR",
        description: "",
        label: "Price",
        required: false,
      },
      id: "rmprnrybcjbcb",
      name: "FREI SPRECHEN - Impulse, Austausch, Netzwerken",
      rsvp_limit: 50,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1591637400000,
      local_date: "2020-06-08",
      local_time: "19:30",
      updated: 1580928105000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      venue: {
        id: 26845930,
        name: "Hotel Olympic",
        lat: 48.13034439086914,
        lon: 11.569995880126953,
        repinned: true,
        address_1: "Hans-Sachs-Straße 4",
        city: "München",
        country: "de",
        localized_country_name: "Germany",
      },
      group: {
        created: 1580846157000,
        name: "FREI SPRECHEN - Impulse, Austausch, Netzwerken",
        id: 33292811,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "FREI-SPRECHEN-Impulse-Austausch-Netzwerken",
        who: "Mitglieder",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link:
        "https://www.meetup.com/FREI-SPRECHEN-Impulse-Austausch-Netzwerken/events/rmprnrybcjbcb/",
      description:
        "<p>Frei und tief verbunden – Beziehungen in unsicheren Zeiten<br/>Wieviel Nähe brauchen wir und wie viel Distanz? Wie regeln wir das?<br/>Kann Liebe wirklich vertrauen und loslassen?</p> <p>19:00 Uhr Ankommen<br/>19:30 Impulsvortrag Berührung - Freiheit - Geborgenheit<br/>19:50 Austausch in kleinen Runden<br/>20:30 Moderierter Debrief<br/>20:45 Vorstellungsrunde mal anders<br/>21:00 Netzwerken, Menschen kennenlernen, Plaudern<br/>22:00 Ende</p> ",
      how_to_find_us:
        "Das Hotel Olympic ist am besten mit der U-Bahn (Sendlinger Tor) oder der Tram 17 zu erreichen (Haltestelle Müllerstraße).",
      visibility: "public",
      member_pay_fee: false,
    },
    {
      created: 1585579493000,
      duration: 7200000,
      id: "269746192",
      name: "MongoDB Easter Hack 2020",
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1586250000000,
      local_date: "2020-04-07",
      local_time: "11:00",
      updated: 1585579512000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 5,
      group: {
        created: 1308160264000,
        name: "MongoDB User Group Munich",
        id: 2026431,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "MUGMunich",
        who: "Members",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link: "https://www.meetup.com/MUGMunich/events/269746192/",
      description:
        "<p>Für alle, die bereits erste Erfahrungen mit MongoDB gesammelt und nicht nur an Easter Eggs, sondern auch an Easter Hacks interessiert sind, veranstalten wir erstmals dieses Jahr am 07. April um 11 Uhr MEZ einen virtuellen Easter Hack!</p> <p>Lernt zusammen mit unseren MongoDB Experten im Rahmen dieser Websession die Grundlagen von MongoDB Atlas kennen, knackt den Code und sichert Euch Eure MongoDB Easter Hack Überraschung!</p> <p>Jetzt registrieren und Platz sichern! Wichtig: Bitte registriert euch auf der Webseite und nicht nur per RSVP in Meetup (ihr bekommt dann die Einwahldaten für den virtuellen Event zugesendet://www.mongodb.com/webinar/easter-hack-2020</a></p> <p>Wir freuen uns auf euch!</p> ",
      visibility: "public",
      member_pay_fee: false,
    },
    {
      created: 1580849312000,
      duration: 10800000,
      fee: {
        accepts: "cash",
        amount: 20,
        currency: "EUR",
        description: "",
        label: "Price",
        required: false,
      },
      id: "rmprnrybchbgb",
      name: "FREI SPRECHEN - Impulse, Austausch, Netzwerken",
      rsvp_limit: 50,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1588613400000,
      local_date: "2020-05-04",
      local_time: "19:30",
      updated: 1580927730000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      venue: {
        id: 26845930,
        name: "Hotel Olympic",
        lat: 48.13034439086914,
        lon: 11.569995880126953,
        repinned: true,
        address_1: "Hans-Sachs-Straße 4",
        city: "München",
        country: "de",
        localized_country_name: "Germany",
      },
      group: {
        created: 1580846157000,
        name: "FREI SPRECHEN - Impulse, Austausch, Netzwerken",
        id: 33292811,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "FREI-SPRECHEN-Impulse-Austausch-Netzwerken",
        who: "Mitglieder",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link:
        "https://www.meetup.com/FREI-SPRECHEN-Impulse-Austausch-Netzwerken/events/rmprnrybchbgb/",
      description:
        "<p>Vom ICH zum WIR - wie gestalten wir das?<br/>Es gibt viele Wege aus der Ellenbogengesellschaft: Ehrenamt, Genossenschaften, BGE, Polyamorie... aber sind wir schon soweit? Und wie gestalten wir den Kulturwechsel in Teams, Firmen und Beziehungen?</p> <p>Zu Beginn erleben wir in einer Körperübung wie wir unseren Kommunikationsraum weiten und das 'Gegenüber' mit hinein nehmen können. Weniger Konfrontation, mehr gemeinsam schauen.</p> <p>19:00 Uhr Ankommen<br/>19:30 Impuls Leadership Embodiment<br/>19:50 Austausch in kleinen Runden<br/>20:30 Moderierter Debrief<br/>20:45 Vorstellungsrunde mal anders<br/>21:00 Netzwerken, Menschen kennenlernen, Plaudern<br/>22:00 Ende</p> ",
      how_to_find_us:
        "Das Hotel Olympic ist am besten mit der U-Bahn (Sendlinger Tor) oder der Tram 17 zu erreichen (Haltestelle Müllerstraße).",
      visibility: "public",
      member_pay_fee: false,
    },
    {
      created: 1371224928000,
      id: "drpzdgybcgblb",
      name: "Ruby User Group Meetup",
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1586365200000,
      local_date: "2020-04-08",
      local_time: "19:00",
      updated: 1507810525000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      group: {
        created: 1370808069000,
        name: "Munich Rubyshift, Ruby User Group",
        id: 8851722,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Munich-Rubyshift-Ruby-User-Group",
        who: "Rubyists",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link:
        "https://www.meetup.com/Munich-Rubyshift-Ruby-User-Group/events/drpzdgybcgblb/",
      description:
        "<p>We're actively searching for speakers! Want to become one? Ping us!</p> ",
      visibility: "public",
      member_pay_fee: false,
    },
    {
      created: 1582647410000,
      duration: 7200000,
      id: "268979993",
      name: "SRE Republic - Munich",
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1588784400000,
      local_date: "2020-05-06",
      local_time: "19:00",
      updated: 1583933746000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 59,
      venue: {
        id: 26055921,
        name: "Personio GmbH",
        lat: 48.14337921142578,
        lon: 11.555990219116211,
        repinned: true,
        address_1: "Rundfunkplatz 4",
        city: "München",
        country: "de",
        localized_country_name: "Germany",
      },
      group: {
        created: 1547827354000,
        name: "SRE Republic",
        id: 30954885,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "SRE-Republic",
        who: "Members",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link: "https://www.meetup.com/SRE-Republic/events/268979993/",
      description:
        "<p>This will be our fourth meetup in the city of Munich and is certain to be another evening of interesting talks around all things SRE, as well as a fantastic opportunity to network with your peers.</p> <p>Date: Wednesday 6th May 2020<br/>Time: 6:30 PM - 9:30 PM<br/>Location: Personio GmbH, Rundfunkplatz 4, 80335 München</p> <p>Doors open for networking @ 6:30</p> <p>Session 1 @ 7:00<br/>Filip Petkovski, Senior Engineer &amp; Pierre Piriou, Senior SRE at Personio<br/>Topic: Enabling Safer Deployments with Gitlab</p> <p>Session 2 @ 7:30<br/>Anthony Moreno, Senior SRE Manager &amp; Boyan Dimitrov, VP of Platform at SIXT<br/>Topic: SRE - from bottom to top and down again</p> <p>Session 3 @ 8:00<br/>To be revealed...</p> <p>More networking and refreshments @ 8:30 - 9:30</p> <p>Looking forward to seeing you there!</p> ",
      visibility: "public",
      pro_is_email_shared: false,
      member_pay_fee: false,
    },
    {
      created: 1582987511000,
      duration: 5400000,
      id: "269086330",
      name: "Begleitgruppe der edulabs zum EBmoocplus2020 6. Treffen",
      rsvp_limit: 15,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1587396600000,
      local_date: "2020-04-20",
      local_time: "17:30",
      updated: 1582987542000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      venue: {
        id: 26589524,
        name: "WikiMUC Wikipedia",
        lat: 48.13136291503906,
        lon: 11.57040786743164,
        repinned: true,
        address_1: "Angertorstraße 3",
        city: "München",
        country: "de",
        localized_country_name: "Germany",
      },
      group: {
        created: 1529326085000,
        name: "edulabs München",
        id: 28867447,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "edulabs-Munchen",
        who: "Mitglieder",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link: "https://www.meetup.com/edulabs-Munchen/events/269086330/",
      description: "Test",
      visibility: "public",
      member_pay_fee: false,
    },
    {
      created: 1581065421000,
      duration: 143940000,
      id: "268530677",
      name: "OUTDOOR COWORKING 2020",
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1593151200000,
      local_date: "2020-06-26",
      local_time: "08:00",
      updated: 1581065462000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      group: {
        created: 1442238396000,
        name: "OUTDOOR COWORKING",
        id: 18930367,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "outdoor-coworking-day",
        who: "Mitglieder",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link: "https://www.meetup.com/outdoor-coworking-day/events/268530677/",
      description:
        "<p>Coworking mal ganz woanders, aber doch im eigenen Van. Mit ganz wem anders, aber doch unter Freunden. Lüftet mit bekannten Unternehmen, Vanlifeworkern und spannenden Personen den Büroalltag mal ordentlich durch. 2019 waren von Firmen wie SIXT, ReCup, andere aus der Sport- oder Automotive-Branche, bis hin zu Agenturen, Freelancern, Fotografen und Influencern alles dabei.<br/>Wir laden Euch ein, Teil unseres #woooday in der Natur zu sein.</p> <p>Buchung unter: www.outdoor-coworking-day.de</p> ",
      visibility: "public",
      member_pay_fee: false,
    },
    {
      created: 1578409630000,
      duration: 104400000,
      id: "267718723",
      name: "H.U.G - Your HR Happening 2020",
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1590656400000,
      local_date: "2020-05-28",
      local_time: "11:00",
      updated: 1581590456000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 11,
      venue: {
        id: 26052459,
        name: "Zenith",
        lat: 48.19461441040039,
        lon: 11.608100891113281,
        repinned: true,
        address_1: "Lilienthalallee 29",
        city: "München",
        country: "de",
        localized_country_name: "Germany",
      },
      group: {
        created: 1510072735000,
        name: "The Future of HR by Personio München",
        id: 26525882,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "The-Future-of-HR-by-Personio",
        who: "Members",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link:
        "https://www.meetup.com/The-Future-of-HR-by-Personio/events/267718723/",
      description:
        "<p>Die H.U.G – unsere Antwort auf öde Personalkongresse!</p> <p>Mittags-Yoga, Friseur und Lego Seriousplay: Unser HR Happening hatte schon 2019 nichts mit 0815-Personalkongressen zu tun. Denn wir von Personio sehen HR jetzt schon als das, was es in Zukunft sein wird:</p> <p>Herausfordernd - Unkonventionell - Gemeinschaftlich</p> <p>Deswegen ist uns ein Personalkongress nicht genug. Wir veranstalten ein ganzes HR Happening mit Fokus auf praxisnahe Vortragsformate (40+ Talks und 40+ interaktive Break-Out-Sessions von mehr als 60 Speaker*innen) und zahlreiche Networking-Möglichkeiten – und das alles wird noch viel größer auf der H.U.G 2020.</p> <p>!! Schnell sein lohnt sich! Sichere dir jetzt dein limitiertes Ticket für nur 299 Euro unter hug.personio.de und spare doppelt: Spare mit dem Code  weitere 10% auf den regulären Ticketpreis. Bitte beachte: Der Eintritt zur H.U.G 2020 nur mit einer offiziellen und gültigen Eintrittskarte möglich. !!</p> <p>Weitere Infos sowie die Tickets bekommst du  ",
      visibility: "public",
      member_pay_fee: false,
    },
    {
      created: 1584390789000,
      duration: 14400000,
      id: "269466520",
      name: "2. agiles PM-Trendforum 2020 (digital) am 07.05.2020",
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1588867200000,
      local_date: "2020-05-07",
      local_time: "18:00",
      updated: 1585580918000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 59,
      group: {
        created: 1430647334000,
        name: "Projektmanagement Meetup Roundtable",
        id: 18574027,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Projektmanagement-Meetup-Roundtable",
        who: "Mitglieder",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link:
        "https://www.meetup.com/Projektmanagement-Meetup-Roundtable/events/269466520/",
      description:
        "<p>Agenda:</p> <p>18:00 Uhr – Begrüßung, Einleitung, Infos zum Ablauf</p> <p>18:15 Uhr – Vortrag 1: -&gt; „Office 365 – Implementierung für das Arbeiten im Homeoffice: Weitere nachhaltige O365 Erweiterungen für die Bereiche Ideenmanagement, Business Cases und Projektkollaboration mit der Edison 365 IT-Suite</p> <p>Vortrag Herr Andreas Hock, Partner 3Pworx GmbH</p> <p>Aufgrund der derzeitigen Corona Krise sind gut ausgebaute und werthaltige Cloud- und Homeoffice Lösungen in aller Munde. Das Arbeiten von zu Hause aus soll vor allem Spaß machen und auch aus der Sicht der Produktivität ein hohes Zielmaß erreichen.</p> <p>Eine der führenden Lösungen, um effizient und professionell vom Homeoffice aus arbeitsfähig zu sein ist Office 365.</p> <p>Office 365 bietet vor allem interessante Lösungen und Apps aus dem Bereich der digitalen Zusammenarbeit, wie MS Teams, SharePoint, usw. Agile Methoden werden ebenfalls reichlich unterstützt.</p> <p>Dieses vorhandene Toolpaket kann durch Lösungen aus dem Bereich Ideenmanagement, Business Cases und Projekt-Kollaboration mit den fertigen Edison 365 Produktlösungen intelligent und nachhaltig erweitert werden.</p> <p>Die nahtlose Integration ins Office 365 Umfeld ist sehr einfach darstellbar. Weitere Schnittstellen zu MS Teams, usw. sind schlüsselfertig.</p> <p>Einen ersten Überblick der Produkte finden Sie hier: ",
      visibility: "public",
      member_pay_fee: false,
    },
    {
      created: 1581059659000,
      duration: 180000000,
      id: "268529977",
      name: "#GlobalAzure 2020 Munich will be virtual - stay tuned",
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1587628800000,
      local_date: "2020-04-23",
      local_time: "10:00",
      updated: 1584004337000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 67,
      venue: {
        id: 26051517,
        name: "Microsoft Germany GmbH",
        lat: 48.177696228027344,
        lon: 11.593815803527832,
        repinned: true,
        address_1: "Walter-Gropius-Straße 5",
        city: "München",
        country: "de",
        localized_country_name: "Germany",
      },
      group: {
        created: 1562061882000,
        name: "Azure DEV Meetup Munich",
        id: 32304402,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Azure-DEV-Munich",
        who: "Azure native",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link: "https://www.meetup.com/Azure-DEV-Munich/events/268529977/",
      description:
        "<p>We have to inform you about some changes to the #GlobalAzure event and so for the #GlobalAzure Munich Event. These changes are globally hitting to all attendees of #GlobalAzure Events.</p> <p>The #GlobalAzure Admin Team informed us about this: </p> <p>We support this decision fully as we have the same conern for health of our local community.</p> <p>But wait! #GlobalAzure will go virtual! Stay tuned and we will share all information here!</p> <p>We are prepping to have an online #GlobalAzure Event all over the world. Our Speaker line-up will hopefully be available online for you!</p> <p>In these times, we think, this is the best to stay together and to show the power of communities.</p> <p>Thank you all, looking forward to have you online :)</p> <p>Stay safe,<br/>Best regards</p> <p>The #GlobalAzure Munich Orga Team</p> ",
      visibility: "public",
      pro_is_email_shared: false,
      member_pay_fee: false,
    },
    {
      created: 1584390889000,
      duration: 14400000,
      id: "269466550",
      name: "3. agiles PM-Trendforum 2020 (digital) am 25.06.2020",
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1593100800000,
      local_date: "2020-06-25",
      local_time: "18:00",
      updated: 1584390889000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 8,
      group: {
        created: 1430647334000,
        name: "Projektmanagement Meetup Roundtable",
        id: 18574027,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Projektmanagement-Meetup-Roundtable",
        who: "Mitglieder",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link:
        "https://www.meetup.com/Projektmanagement-Meetup-Roundtable/events/269466550/",
      description: "<p>Agenda folgt in Kürze</p> ",
      visibility: "public",
      member_pay_fee: false,
    },
    {
      created: 1581805886000,
      duration: 7200000,
      id: "268739229",
      name:
        "Product-Led Growth Transformation: Considerations & Best Practices",
      rsvp_limit: 50,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1588177800000,
      local_date: "2020-04-29",
      local_time: "18:30",
      rsvp_close_offset: "PT8H",
      updated: 1583162660000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 27,
      venue: {
        id: 26343782,
        name: "DROSSEL & zehner",
        lat: 48.132083892822266,
        lon: 11.56650161743164,
        repinned: false,
        address_1: "Thalkirchner Str. 10",
        city: "München",
        country: "de",
        localized_country_name: "Germany",
      },
      group: {
        created: 1549469074000,
        name: "The SaaS Meetup",
        id: 31102354,
        join_mode: "approval",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "The-SaaS-Meetup",
        who: "Members",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link: "https://www.meetup.com/The-SaaS-Meetup/events/268739229/",
      description:
        "<p>Product-Led Growth (PLG) is a new buzzword in SaaS. Companies like Calendly, Zoom, Drift and Slack have had hyper growth due to this strategy. Join us to know from 12-months intensive research and PLG expert who consults many SaaS companies on this and learn from her experience. She's especially coming for this meetup from Athens.</p> <p>Topic: Product-Led Growth Transformation: Considerations &amp; Best Practices</p> <p>Session details:<br/>Product-Led Growth Fundamentals</p> <p>Overview of the characteristics driving the PLG Model<br/>The Product (Led) experience imperative</p> <p>Traditional model vs. Product-Led Growth GTM model.</p> <p>Breakdown of the GTM Model: Considerations &amp; best practices of the pricing models following PLG (Free trial vs. Freemium).<br/>Reconsidering the sales funnel benchmarks and KPIs: Product-Qualified leads criteria &amp; KPIs to be considered<br/>Departments &amp; stakeholders involved across the customer lifecycle.<br/>Mind the customer...segment: How PLG balances product delivery across different customer segments (High vs. Low trajectory customers)<br/>The customer feedback imperative: Why both customer &amp; user feedback need to be assessed when organizations deliver a PLG model.<br/>Product Experience techstack: The tools SaaS organizations need to assess and manage product experience.</p> <p>Speaker's Bio:<br/>Despina is the founder of ReinventGrowth and a Product-Led Growth &amp; user onboarding strategist with over 10 years of professional experience in SaaS. After she mapped down Product-Led Growth practices across the SaaS industry, she made her life's mission to revolutionize how organizations reach their desired growth levels by leveraging onboarding outcomes and product (led) engagements.</p> <p>Agenda:<br/>18:30: Gates open and we welcome everyone<br/>19:00: Session &amp; QA<br/>20:00: Networking and snacks</p> ",
      how_to_find_us: "DROSSEL & zehner",
      visibility: "public",
      member_pay_fee: false,
    },
    {
      created: 1581507452000,
      duration: 10800000,
      id: "268652473",
      name: "Rhino Stammtisch München",
      rsvp_limit: 12,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1590512400000,
      local_date: "2020-05-26",
      local_time: "19:00",
      updated: 1583244609000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      venue: {
        id: 26086481,
        name: "Cafe Blue",
        lat: 48.12382507324219,
        lon: 11.54822826385498,
        repinned: true,
        address_1: "Implerstraße 2",
        city: "München",
        country: "de",
        localized_country_name: "Germany",
      },
      group: {
        created: 1562069315000,
        name: "Rhino 3D CAD Meetup München",
        id: 32304959,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Rhino-3D-CAD-Meetup-Munchen",
        who: "Mitglieder",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link:
        "https://www.meetup.com/Rhino-3D-CAD-Meetup-Munchen/events/268652473/",
      description:
        "<p>Etwas trinken und über Rhino, 3D, CAD, Grasshopper, Projekte und Ideen austauschen. Natürlich vor allem Spaß haben.</p> ",
      how_to_find_us: "Nach Rhino Fragen",
      visibility: "public",
      member_pay_fee: false,
    },
    {
      local_time: "19:00",
      local_date: "2020-04-28",
      link:
        "https://www.meetup.com/Software-Performance-Meetup-Group/events/268603039/",
      visibility: "public_limited",
      group: {
        created: 1400662449000,
        name: "Software Performance Meetup Group",
        id: 14586172,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Software-Performance-Meetup-Group",
        who: "Performance Management Worker",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      waitlist_count: 8,
      yes_rsvp_count: 35,
      duration: 7200000,
      time: 1588093200000,
      utc_offset: 7200000,
      name: "23rd Software Performance Meetup",
      id: "268603039",
    },
    {
      created: 1581639659000,
      duration: 10800000,
      id: "268694942",
      name: "Unternehmertreffen & Start up-Event in München",
      rsvp_limit: 30,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1591545600000,
      local_date: "2020-06-07",
      local_time: "18:00",
      updated: 1582394104000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 3,
      venue: {
        id: 26865361,
        name: "The Flushing Meadows Bar, Frauenhoferstraße 32, 80469 München",
        lat: 48.128822326660156,
        lon: 11.574684143066406,
        repinned: false,
        address_1: " Frauenhoferstraße 32, 80469 München",
        city: "München",
        country: "DE",
        localized_country_name: "Germany",
      },
      group: {
        created: 1581635431000,
        name: "Unternehmertreffen and Start up-Event München",
        id: 33341612,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Unternehmertreffen-Start-up-Event-Munchen",
        who: "Mitglieder",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link:
        "https://www.meetup.com/Unternehmertreffen-Start-up-Event-Munchen/events/268694942/",
      description:
        "<p>DAS UNTERNEHMERTREFFEN „MÜNCHEN“ STARTUP EVENT</p> <p>INVESTOREN / BUSINESS-ANGEL*<br/>*mehr Details in der Beschreibung</p> <p>Das Unternehmertreffen Munich-Milan ist das Forum für Geschäftsfreunde in ganz Deutschland. Wir hören gemeinsam spannende Vorträge, veranstalten Aktionen, haben Zeit für informelle Gespräche und bahnen Geschäfte an.</p> <p>Wir sind überparteilich und unabhängig. Und vor allem: Wir haben viel Spaß am Netzwerken!</p> <p>Zahlreiche UNTERNEHMER und STARTUP UNTERNEHMEN aus dem Raum München nehmen teil und freuen sich über Jeden, der unser Netzwerk weiter verstärkt. AUCH STUDENTEN MIT GUTEN IDEEN SIND HERZLICH WILLKOMMEN.</p> <p>Informationen und Tickets finden sich unter:",
      visibility: "public",
      member_pay_fee: false,
    },
    {
      created: 1582105561000,
      duration: 118800000,
      id: "268822427",
      name: "ContainerDays 2020 - Super Early Bird Special",
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1592892000000,
      local_date: "2020-06-23",
      local_time: "08:00",
      updated: 1583147451000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 13,
      group: {
        created: 1446783141000,
        name: "München Kubernetes/Cloud-Native Meetup",
        id: 19095162,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Munchen-Kubernetes-Meetup",
        who: "Kubernauts",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link:
        "https://www.meetup.com/Munchen-Kubernetes-Meetup/events/268822427/",
      description:
        "<p>ContainerDays 2020 is ready to start! From June 22-24, the international container community will gather again at the Harbor Museum in Hamburg to discuss the past, present, and future of cloud native technologies.</p> <p>Just like all the previous years, ContainerDays will be loaded with exciting deeply technical talks and hands-on workshops with the focus on #Microservices, #DistributedApps, #Kubernetes #CloudNative, #CICD and #DevOps. This is your chance to meet like-minded container enthusiasts.</p> <p>You can use the community code (#CDS20_20%@COMMUNITY) and get 20% discount of the regular tickets price.</p> <p>Join us and get inspired!</p> ",
      visibility: "public",
      pro_is_email_shared: false,
      member_pay_fee: false,
    },
  ],
};

export { mockEvents };
