const mockEvent = {
  created: 1579163951000,
  duration: 10800000,
  id: "ddhzmrybcgbtb",
  name: "Drupal User Group Munich @EineWeltHaus",
  rsvp_limit: 15,
  date_in_series_pattern: false,
  status: "upcoming",
  time: 1586970000000,
  local_date: "2020-04-15",
  local_time: "19:00",
  updated: 1583154863000,
  utc_offset: 7200000,
  waitlist_count: 0,
  yes_rsvp_count: 3,
  venue: {
    id: 26078691,
    name: "EineWeltHaus",
    lat: 48.137691497802734,
    lon: 11.55286979675293,
    repinned: true,
    address_1: "Schwanthalerstraße 80",
    city: "München",
    country: "de",
    localized_country_name: "Germany",
  },
  group: {
    created: 1410086988000,
    name: "München Drupal User Group Meetup",
    id: 16845232,
    join_mode: "open",
    lat: 48.13999938964844,
    lon: 11.579999923706055,
    urlname: "Munchen-Drupal-User-Group-Meetup",
    who: "Drupalistas",
    localized_location: "München, Germany",
    state: "",
    country: "de",
    region: "en_US",
    timezone: "Europe/Berlin",
  },
  link:
    "https://www.meetup.com/Munchen-Drupal-User-Group-Meetup/events/ddhzmrybcgbtb/",
  description:
    "<p>Das Meetup ist sowohl für Drupal-AnwenderInnen, -EntwicklerInnnen, -EinsteigerInnen als auch Professionals geeignet. Wir reden nicht nur über Drupal, sondern auch über Community, React, Vue.js, Docker, Symfony, PHP, UX und viele andere Dinge. Andere Communities sind bei uns herzlich Willkommen!</p> <p>The meetup is for any level of Drupal user. We are not talking Drupal only but also about community, React, Vue.js, Docker Symfony, PHP, UX and much more stuff. Other communities are very welcome.</p> <p>---<br/>Vortrag 1 / Talk 1 -<br/>---<br/>Vortrag 2 /Talk 2 - tbd<br/>---</p> <p>Wir suchen immer nach interessanten Themen! Wenn du interessiert daran bist, einen Vortrag oder ein interessantes Projekt vorzustellen (deutsch oder englisch entscheidest du!), melde dich bei uns.</p> <p>Im Anschluss der Talks gibt es genügend Zeit für Diskussion und Networking. Wir sehen uns dort!</p> <p>---</p> <p>If you are interested in giving a talk or to speak about a interesting project, drop us a line. We are always looking for talks.</p> <p>Followed by discussion and networking.<br/>See you there!</p> ",
  how_to_find_us: "Raum 109. Bitte den Raumbelegungsplan am Eingang beachten.",
  visibility: "public",
  member_pay_fee: false,
};

export { mockEvent };
